### ISSUE TITLE
Can we nest all plugins directly underneath src/

### ISSUE THREAD

**Issue by brendanfalk** [withfig/plugins#3]
Or alternatively, have all the plugins in a folder at the top level called plugins and the remaining stuff in a folder called utils or something like that?

Should be super ridiculously easy for someone to get to the list of plugins. No concern about which folder to click on. We are almost certainly going to end up throwing a bunch of shit into src/ and it will be harder to change this later

Summary: List of plugins should be one level deep not two and should be in a very obvious folder name

**Comment by yavko** [comment]
I'll make a pr for it later!

**Comment by grant0417** [comment]
Just to add to the structure we want it will look like this:
```
| plugins
| - ohmyzsh
| --- index.ts
| --- image.png
| - pure
| --- `index.ts
```

The top level directory `plugins` will have folders for each plugins with a `index.ts` and any images/other assets we want.

**Comment by grant0417** [comment]
This is now implemented in `staging`

**Comment by yavko** [comment]
Sorry I was busy yesterday.
