### ISSUE TITLE
plugin-format.md is a broken link

### ISSUE THREAD

**Issue by WingofaGriffin** [withfig/plugins#4]
It looks like [plugin-format.md](https://github.com/withfig/plugins/blob/main/manifest-format.md) has been removed from the repo, but remains in the readme. I see no comparison to it in the docs website.

**Comment by grant0417** [comment]
@WingofaGriffin, thanks, we really need to do a proper README write up.

**Comment by grant0417** [comment]
@WingofaGriffin, much better plugin format docs are now here! Still working on them but should be able to make most plugins functional with them.
