### ISSUE TITLE
Spaceship Prompt Configuration

### ISSUE THREAD

**Issue by lobosan** [withfig/plugins#50]
Hi, it would be great if you could add this property to the configuration

`SPACESHIP_PACKAGE_SHOW=false/true`

<img width="636" alt="image" src="https://github.com/withfig/plugins/assets/314886/f0048197-572d-4b7a-9544-d0c76230a022">

**Comment by grant0417** [comment]
All of the configs are stored in this file if you want to contribute: https://github.com/withfig/plugins/blob/e2984fd15491a6f54b3c95b0f7f2a386a4102971/plugins/spaceship-prompt/index.ts

**Comment by lobosan** [comment]
@grant0417 I just created this PR https://github.com/withfig/plugins/pull/51/files
